### ISSUE TITLE
cleanly separate api calls

### ISSUE THREAD

**Issue by arscan** [arscan/habitrpg-txt#11]

**Comment by arscan** [comment]
hey @wizonesolutions, I'm about to push a major rewrite, which is now in the api-refactor branch.  Any interest in trying out that branch to see how it performs on your mac?  I put in refreshes everywhere that I felt appropriate (but nowhere else), and i'm curious if I will have to add in the entire-page-rewrites that I did before to support macs.  If so, I may add a "hard-refresh" flag for mac users, because it annoys me that my computer is doing more work than it has to.

The rewrite doesn't really add any functionality (except a debug window, open with "~", "r" to pull stuff from the site), but it rationalized the entire codebase so I can now start adding stuff like purchases, parties, etc.

Thanks!

**Comment by wizonesolutions** [comment]
Definitely interested, I'll try tonight or tomorrow

**Comment by arscan** [comment]
added search, which is pretty handy.

**Comment by arscan** [comment]
fyi, i just merged it into master.  note: `node index.js` to start it now.

**Comment by wizonesolutions** [comment]
Giving it a shot tomorrow morning.

**Comment by wizonesolutions** [comment]
It's a little better, but still refreshes erratically and usually doesn't show all my tasks. Also, it refreshes in such a way that it's hard to tell what my keypress actually did. And I think I have to hit the up key to move down? Weird stuff like that.

**Comment by arscan** [comment]
Heh, the up key to move down was an easy fix (I usually use j and k so didn't notice that i broke that).

sorry on the other issues.  guess i'll have to add in full screen refreshes like before.

**Comment by arscan** [comment]
If you press "r" when it is broken does that fix everything (temporarily)?

**Comment by arscan** [comment]
alright @wizonesolutions ... i did a full rewrite and it no longer uses ncurses.  It basically just uses straight-up terminal command codes to move the cursor around... so I imagine that it should work fine in osx.  it works fine in tmux, which was also broken before.

press "?" to toggle the help dialog for key bindings.

**Comment by wizonesolutions** [comment]
Alright let me give it a shot today or soon

**Comment by wizonesolutions** [comment]
@arscan :clap: :clap: :clap:

This works TONS better. I can actually see the interface, woo!

I'll file separate issues if needed but just wanted to give feedback.

How often does it refresh everything?

**Comment by arscan** [comment]
"I can actually see the interface" -- hahaha, that is an improvement :)

It refreshes every 10 seconds right now.  You can press "r" to force a refresh.

Yeah, I'd love the feedback, or if you have any feature ideas let me know.
