### ISSUE TITLE
Mega-broken on my Mac (OS X 10.7.5)

### ISSUE THREAD

**Issue by wizonesolutions** [arscan/habitrpg-txt#17]
Here is a screenshot of what happens. My API credentials look to be correct. I am using a `config.json`.

![Bildschirmfoto 2013-04-08 um 05 36 16](https://f.cloud.github.com/assets/344116/349969/8d77e278-9ffd-11e2-9bc3-b10b491f6572.png)

**Comment by arscan** [comment]
Thanks!
