### ISSUE TITLE
habitrpg-ncurses unusable in tmux

### ISSUE THREAD

**Issue by AdrienLemaire** [arscan/habitrpg-txt#24]
Hello,

Using rxvt-unicode, it seems I can use the program finely (didn't test it much).
But if I try to run the program in a tmux panel, then it becomes extremely slow (about 6 seconds to refresh the screen).

Thanks for looking at this issue :)

Cordially

**Comment by arscan** [comment]
Ah, tmux.  I'll try that out and will see whats up.  Thanks!

**Comment by arscan** [comment]
almost fixed... i think. doing a rewrite so it doesn't use ncurses any more

**Comment by arscan** [comment]
alright, did a full rewrite.  so if you are interested in using this it should work in tmux now (or at least it works for me).  thanks!
