### ISSUE TITLE
Deleting a task makes it unresponsive

### ISSUE THREAD

**Issue by pgrosslicht** [arscan/habitrpg-txt#42]
Whenever I delete a task, the program becomes almost completely unresponsive, the only thing that still works is pressing `?` to get the help menu. You have to terminate it with `Ctrl-C`.

**Comment by arscan** [comment]
whoops, that's no good.  forgot a simple break statement.  i should have reviewed the pull request from last week a little closer.  thanks for reporting these issues!

cc4c942e47c16fa5c708b3365a119a94d2d01b9a
